# Generated by Django 5.0.2 on 2024-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compete',
            name='compete_type',
            field=models.CharField(blank=True, choices=[('Coding/Programming', 'Coding/Programming'), ('Innovation/Startup', 'Innovation/Startup'), ('Design/UX', 'Design/UX')], max_length=20, null=True),
        ),
    ]
